### ISSUE TITLE
gist this

### ISSUE THREAD

**Issue by mehranhadidi** [omidakhavan/I-USE-THIS#1]
ino mitooni gist koni k rahat bashe. gist vase injoori karast :dancer:

**Comment by omidakhavan** [comment]
gist daram :D 
https://gist.github.com/omidakhavan/f5f0417e68080f63cfae0a629db46d32
midoonam chiye gozashtam baghiye faiz bebaran :))

**Comment by mehranhadidi** [comment]
kheili kare ghashangi kardi repo ham gozashty? :)))
